package com.webtopdf.service;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.properties.TextAlignment;
import com.webtopdf.dto.PaperResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PdfGeneratorService {

    private static final Logger log = LoggerFactory.getLogger(PdfGeneratorService.class);

    private static final DeviceRgb PRIMARY_COLOR   = new DeviceRgb(22,  60, 130);
    private static final DeviceRgb HEADING_COLOR   = new DeviceRgb(37,  99, 235);
    private static final DeviceRgb SUBHEAD_COLOR   = new DeviceRgb(71,  85, 105);
    private static final DeviceRgb TEXT_COLOR      = new DeviceRgb(30,  30,  30);
    private static final DeviceRgb SEPARATOR_COLOR = new DeviceRgb(203, 213, 225);

    public byte[] generate(PaperResponse paper) throws Exception {
        log.info("Generating PDF for paper: {}", paper.title());

        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            PdfWriter   writer = new PdfWriter(baos);
            PdfDocument pdf    = new PdfDocument(writer);
            Document    doc    = new Document(pdf, PageSize.A4);
            doc.setMargins(60, 65, 60, 65);

            PdfFont titleFont  = PdfFontFactory.createFont(StandardFonts.TIMES_BOLD);
            PdfFont headFont   = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            PdfFont bodyFont   = PdfFontFactory.createFont(StandardFonts.TIMES_ROMAN);
            PdfFont italicFont = PdfFontFactory.createFont(StandardFonts.TIMES_ITALIC);

            // Cover / title block
            doc.add(new Paragraph("\n\n\n"));
            doc.add(new Paragraph(paper.title())
                    .setFont(titleFont).setFontSize(22).setFontColor(PRIMARY_COLOR)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(4));
            doc.add(new Paragraph("Generated by Link2Paper · " + java.time.LocalDate.now())
                    .setFont(italicFont).setFontSize(10).setFontColor(SUBHEAD_COLOR)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(20));
            addSeparator(doc);

            // Abstract
            doc.add(heading("Abstract", headFont));
            doc.add(body(paper.abstractText(), italicFont));
            addSeparator(doc);

            // Body sections
            addSection(doc, "1. Introduction", paper.introduction(), headFont, bodyFont);
            addSection(doc, "2. Methodology",  paper.methodology(),  headFont, bodyFont);
            addSection(doc, "3. Discussion",   paper.discussion(),   headFont, bodyFont);
            addSection(doc, "4. Conclusion",   paper.conclusion(),   headFont, bodyFont);

            // References
            doc.add(heading("References", headFont));
            List<String> refs = paper.references();
            if (refs == null || refs.isEmpty()) {
                doc.add(body("No references provided.", bodyFont));
            } else {
                for (int i = 0; i < refs.size(); i++) {
                    doc.add(new Paragraph("[" + (i + 1) + "] " + refs.get(i))
                            .setFont(bodyFont).setFontSize(10).setFontColor(TEXT_COLOR).setMarginBottom(4));
                }
            }

            doc.close();
            log.info("PDF generated, size: {} bytes", baos.size());
            return baos.toByteArray();
        }
    }

    private void addSection(Document doc, String title, String body, PdfFont headFont, PdfFont bodyFont) {
        doc.add(heading(title, headFont));
        doc.add(body(body, bodyFont));
    }

    private Paragraph heading(String text, PdfFont font) {
        return new Paragraph(text).setFont(font).setFontSize(13).setFontColor(HEADING_COLOR)
                .setMarginTop(14).setMarginBottom(6);
    }

    private Paragraph body(String text, PdfFont font) {
        return new Paragraph(text == null ? "" : text).setFont(font).setFontSize(11)
                .setFontColor(TEXT_COLOR).setTextAlignment(TextAlignment.JUSTIFIED)
                .setFirstLineIndent(20).setMarginBottom(8).setFixedLeading(16);
    }

    private void addSeparator(Document doc) {
        SolidLine line = new SolidLine(0.5f);
        line.setColor(SEPARATOR_COLOR);
        doc.add(new LineSeparator(line).setMarginTop(8).setMarginBottom(8));
    }
}
